"""fand-calibrate: PWM perturbation sweep + zones.yaml generation.

Two-phase, operator-supervised. The output is a *template* zones.yaml — the
operator picks each zone's target sensors and target temps by hand based on
physical case layout, because no amount of probing tells us "this is the front
intake vs the rear exhaust." We DO auto-discover:

  1. PWM ↔ fan-tach mapping (for fault detection at runtime)
  2. pwm_min per channel (the lowest PWM value at which the fan still spins)

Run with:  /opt/comfyui/fand/.venv/bin/python -m fand.calibrate
Requires root (writes to /sys/class/hwmon).
"""

from __future__ import annotations

import argparse
import logging
import os
import sys
import time
from pathlib import Path

from .actuators import Actuators
from .sensors import Sensors, find_hwmon_by_name

log = logging.getLogger("fand-calibrate")


DEFAULT_BOOTSTRAP_CURVE = [(40.0, 100), (60.0, 160), (75.0, 210), (85.0, 255)]


def _read_tach(hw: Path, fan_key: str) -> int:
    try:
        return int((hw / f"{fan_key}_input").read_text().strip())
    except (OSError, ValueError):
        return 0


def _settle(seconds: float) -> None:
    log.info("  settle %.0fs...", seconds)
    time.sleep(seconds)


def map_pwm_to_tach(actuators: Actuators, hw: Path, fan_keys: list[str]) -> dict[str, str | None]:
    """For each PWM channel, find which fan tach responds the most.

    Strategy: set every other PWM to 160 (steady), then for the channel under
    test bounce 80 → 220 → 80 and record the tach with the biggest swing.
    Returns {pwm_channel: fan_key_or_None}.
    """
    mapping: dict[str, str | None] = {}
    channels = list(actuators.handles.keys())

    for target in channels:
        log.info("probing %s …", target)
        # Hold every other channel at 160 (60%) so they don't drift during probe
        for ch in channels:
            actuators.set_pwm(ch, 160)
        _settle(3.0)

        # Low step
        actuators.set_pwm(target, 80)
        _settle(4.0)
        low = {k: _read_tach(hw, k) for k in fan_keys}

        # High step
        actuators.set_pwm(target, 220)
        _settle(4.0)
        high = {k: _read_tach(hw, k) for k in fan_keys}

        deltas = {k: high[k] - low[k] for k in fan_keys}
        log.info("  deltas: %s", deltas)

        best = max(deltas.items(), key=lambda kv: kv[1])
        if best[1] < 100:  # tiny swing -> probably not connected
            log.info("  -> %s: no fan responded (deltas all small)", target)
            mapping[target] = None
        else:
            mapping[target] = best[0]
            log.info("  -> %s drives %s (Δ %d RPM)", target, best[0], best[1])

        # Return to neutral
        actuators.set_pwm(target, 160)

    return mapping


def find_pwm_min(actuators: Actuators, hw: Path, channel: str, tach: str | None) -> int:
    """Step PWM down until the fan stalls (or we hit a safety floor).

    Returns the lowest PWM at which the fan still reports ≥200 RPM, plus a
    small safety margin. If no tach is owned by this channel, returns 80 as a
    conservative default.
    """
    if not tach:
        return 80

    actuators.set_pwm(channel, 200)
    _settle(3.0)

    last_spinning = 100
    for v in range(100, 19, -10):
        actuators.set_pwm(channel, v)
        _settle(3.0)
        rpm = _read_tach(hw, tach)
        log.info("  %s @ pwm=%d -> %d RPM", channel, v, rpm)
        if rpm < 200:
            break
        last_spinning = v
    # Margin: +20 PWM over the last spinning value, capped at 100
    return min(100, last_spinning + 20)


def render_zones_yaml(
    pwm_to_tach: dict[str, str | None],
    pwm_min: dict[str, int],
    hw: Path,
    out_path: Path,
) -> None:
    """Write a template zones.yaml. Operator fills target_sensors per zone."""
    lines: list[str] = []
    lines.append("# Generated by fand-calibrate on " + time.strftime("%Y-%m-%dT%H:%M:%S"))
    lines.append("# Edit `target_sensors` for each zone before starting fand.")
    lines.append("# - chip: hwmon `name` file (e.g. nct6799, k10temp, nvme, spd5118).")
    lines.append("# - label: sensor label (e.g. Tctl, SYSTIN, Composite, temp1).")
    lines.append("# - target_c: temp we want this fan to hold below.")
    lines.append("# - critical_c: hard floor; if exceeded, all fans -> 255 + alert.")
    lines.append("zones:")
    for pwm_ch, tach in pwm_to_tach.items():
        if tach is None:
            lines.append(f"  # {pwm_ch}: no responding fan detected; not managed")
            continue
        zone_name = pwm_ch  # operator can rename
        lines.append(f"  - name: {zone_name}")
        lines.append(f"    pwm_channel: {pwm_ch}")
        lines.append(f"    fan_tach: {tach}_input")
        lines.append(f"    pwm_min: {pwm_min.get(pwm_ch, 80)}")
        lines.append(f"    # TODO: set primary + secondary target sensors")
        lines.append(f"    target_sensors:")
        lines.append(f"      - chip: nct6799")
        lines.append(f"        label: SYSTIN")
        lines.append(f"        target_c: 65.0")
        lines.append(f"        critical_c: 80.0")
        lines.append(f"    bootstrap_curve:  # temp_c -> pwm fallback before learning")
        for t, p in DEFAULT_BOOTSTRAP_CURVE:
            lines.append(f"      - [{t}, {p}]")
        lines.append("")

    text = "\n".join(lines) + "\n"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if out_path.exists():
        backup = out_path.with_suffix(out_path.suffix + ".bak")
        out_path.rename(backup)
        log.info("backed up existing %s -> %s", out_path, backup)
    out_path.write_text(text)
    log.info("wrote %s", out_path)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="/etc/fand/zones.yaml")
    ap.add_argument("--chip", default="nct6799")
    args = ap.parse_args(argv)

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(name)s %(levelname)s: %(message)s",
    )

    if os.geteuid() != 0:
        log.error("calibrate must be run as root (PWM writes need it)")
        return 1

    hw = find_hwmon_by_name(args.chip)
    if hw is None:
        log.error("hwmon chip %s not found", args.chip)
        return 2

    # Pre-flight: warn if GPU is hot or active (results will be skewed)
    s = Sensors()
    obs = s.read_all()
    if obs.gpu and obs.gpu["util_pct"] > 5:
        log.warning(
            "GPU util = %.0f%% — calibration assumes IDLE system, please stop ML workloads",
            obs.gpu["util_pct"],
        )
    if obs.gpu and obs.gpu["temp_c"] > 50:
        log.warning(
            "GPU temp = %.0f°C — let the system cool to ~40°C before calibrating",
            obs.gpu["temp_c"],
        )

    # Find all pwm channels on this chip
    channels: list[str] = []
    for p in sorted(hw.glob("pwm*")):
        if "_" in p.name:
            continue  # skip pwm1_enable etc.
        channels.append(p.name)
    fan_keys = [p.name.removesuffix("_input") for p in sorted(hw.glob("fan*_input"))]
    log.info("chip %s — pwm channels: %s, fan tachs: %s", args.chip, channels, fan_keys)

    log.info("starting calibration. Press Ctrl-C to abort (restores BIOS mode).")
    with Actuators(channels, chip_name=args.chip) as actuators:
        log.info("phase 1: PWM ↔ fan-tach mapping")
        pwm_to_tach = map_pwm_to_tach(actuators, hw, fan_keys)

        log.info("phase 2: pwm_min discovery per channel")
        pwm_min: dict[str, int] = {}
        for ch in channels:
            log.info("finding pwm_min for %s ...", ch)
            pwm_min[ch] = find_pwm_min(actuators, hw, ch, pwm_to_tach.get(ch))
            # Restore to neutral before next channel
            actuators.set_pwm(ch, 160)

    # We're back in BIOS mode after the context exit. Write the template.
    render_zones_yaml(pwm_to_tach, pwm_min, hw, Path(args.out))

    log.info("done.")
    log.info("next steps:")
    log.info("  1. edit %s -- set target_sensors per zone", args.out)
    log.info("  2. systemctl start fand")
    log.info("  3. fand-ctl status")
    return 0


if __name__ == "__main__":
    sys.exit(main())
